update oai5g-rru repo

diff --git a/roles/5g/oai/setup/tasks/main.yml b/roles/5g/oai/setup/tasks/main.yml
--- a/roles/5g/oai/setup/tasks/main.yml
+++ b/roles/5g/oai/setup/tasks/main.yml
@@ -1,5 +1,5 @@
 ---
-- name: RESTART_OAI_SETUP
+- name: START_OAI_SETUP
   ansible.builtin.meta: noop
 
 - name: Check if yq is already installed
@@ -46,13 +46,13 @@
     set -e
     if command -v curl >/dev/null 2>&1; then
       curl -L --fail \
-        "https://raw.githubusercontent.com/Ziyad-Mabrouk/oai5g-rru/{{ tag_oai5g_rru }}/testing/prepare-demo-oai.sh" \
+        "https://raw.githubusercontent.com/{{ prefix_oai5g-rru }}/{{ tag_oai5g_rru }}/testing/prepare-demo-oai.sh" \
         -o "{{ prepare_demo_script }}"
     elif command -v wget >/dev/null 2>&1; then
       wget -O "{{ prepare_demo_script }}" \
-        "https://raw.githubusercontent.com/Ziyad-Mabrouk/oai5g-rru/{{ tag_oai5g_rru }}/testing/prepare-demo-oai.sh"
+        "https://raw.githubusercontent.com/{{ prefix_oai5g-rru }}/{{ tag_oai5g_rru }}/testing/prepare-demo-oai.sh"
     else
-      echo "Neither curl nor wget found" >&2
+      echo "Couldn't retrieve prepare-demo-oai.sh script from oai5g-rru repo" >&2
       exit 1
     fi
     chmod 0755 "{{ prepare_demo_script }}"
@@ -140,7 +140,8 @@
   ansible.builtin.lineinfile:
     path: "{{ prepare_demo_script }}"
     regexp: '^LOCAL_CORE_INTERFACE='
-    line: "LOCAL_CORE_INTERFACE=\"{{ multus_ran_if if fhi72 | bool else multus_core_if }}\""
+    line: "LOCAL_CORE_INTERFACE=\"{{ multus_core_if }}\""
+    #line: "LOCAL_CORE_INTERFACE=\"{{ multus_ran_if if fhi72 | bool else multus_core_if }}\""
     backrefs: true
 
 - name: Update LOCAL_RAN_INTERFACE variable in prepare-demo-oai.sh
